### ISSUE TITLE
Angular NaNmageDirective error

### ISSUE THREAD

**Issue by GaurangGhinaiya** [Mischi/angularjs-imageupload-directive#34]
`Error: [$injector:unpr] http://errors.angularjs.org/1.2.27/$injector/unpr?p0=aProvider%20%3C-%20a%20%3C-NaNmageDirective
    at Error (native)
    at http://www.example.com/min/admin-production.min.js:19:10395
    at http://www.example.com/min/admin-production.min.js:19:25331
    at Object.c [as get] (http://www.example.com/min/admin-production.min.js:19:24402)
    at http://www.example.com/min/admin-production.min.js:19:25405
    at c (http://www.example.com/min/admin-production.min.js:19:24402)
    at Object.d [as invoke] (http://www.example.com/min/admin-production.min.js:19:24617)
    at http://www.example.com/min/admin-production.min.js:19:29463
    at f (http://www.example.com/min/admin-production.min.js:19:10732)
    at Object.<anonymous> (http://www.example.com/min/admin-production.min.js:19:29430)`

HI i am getting this error while directive call

**Comment by GaurangGhinaiya** [comment]
@Mischi 

`angular.module('imageupload', [])
    .directive('image',  function($q) {...}`
It is not work after uglify. For the param $q may be converted to another name such as a,b,c,f, etc by uglify compiler.

So i convert it to and it works perfectly.

`angular.module('imageupload', [])
    .directive('image', ['$q', function($q) {...}]`

Please change this.
